[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/model/:id"
  to = "/.netlify/functions/model/:id"
  status = 200
